### ISSUE TITLE
Add "pattern generator based on the idea of the book forms of colors"

### ISSUE THREAD

**Issue by Naii** [dypsilon/frontend-dev-bookmarks#271]
http://eskimoblood.github.io/gerstnerizer/

**Comment by dypsilon** [comment]
Not sure how it is useful.

**Comment by Naii** [comment]
@dypsilon It is useful for creating more like artistic background grids. You don't want design bookmarks in your list?

**Comment by neuros1s** [comment]
Thanks, will try it :)

**Comment by Naii** [comment]
@neuros1s You're welcome :+1:
