### ISSUE TITLE
Add Front-End Fundamentals book

### ISSUE THREAD

**Issue by fender** [dypsilon/frontend-dev-bookmarks#295]
Here is a book myself and @carwin just released which can help upcoming front-end developers. It covers the major front-end development topics such as frameworks, automation, styling and dependency management. Hope it can help! https://leanpub.com/front-end-fundamentals

**Comment by kayhadrin** [comment]
-1

Advertisement.

**Comment by fender** [comment]
@kayhadrin Sorry if I have crossed any lines. There are other books in the list and so I thought it would be OK to have ours listed too. Perhaps there were some guidelines I missed about suggesting resources that require purchase? Please let me know and I'll close this issue immediately.

**Comment by JasperGitHub** [comment]
Maybe zhihu can help Chinese fe-engineer improve themself

**Comment by dypsilon** [comment]
Thanks for your contribution. Adding every book abound frontend development would blow up the list quickly. I will revise your addition when we have better tools to scale the list.
