### ISSUE TITLE
Join to translation English to Indonesian 

### ISSUE THREAD

**Issue by rabooe** [dypsilon/frontend-dev-bookmarks#386]
hello Mr., I am a translator, I want to translate English into Indonesian, Because the majority of Indonesian people do not understand English

**Comment by kayhadrin** [comment]
Sure, just for this repo and go for it! 👍

**Comment by rabooe** [comment]
thank you sir, i will mean it

2018-02-11 7:10 GMT+07:00 David <notifications@github.com>:

**Comment by dypsilon** [comment]
Hi Rabo,

thank you for suggesting to create a translation, I really appreciate it.

Sadly, there is no good way to integrate your work right now and it might take a while so you are probably better off just creating your own fork.

Best Regards
Tim
