### ISSUE TITLE
svgjs.com dead link

### ISSUE THREAD

**Issue by Mert18** [dypsilon/frontend-dev-bookmarks#423]
looks like svgjs.com is a gambling site anymore.

**Comment by GurjinderSingh** [comment]
https://svgjs.dev/ 
https://github.com/svgdotjs/svg.js

correct site

**Comment by btargac** [comment]
Hi @Mert18 do you have an active merge request for that ?

**Comment by Mert18** [comment]
No, but the last change is made 4 years ago. Nothing would change I guess.
